### ISSUE TITLE
Adding Inertia Tensor

### ISSUE THREAD

**Issue by tgroche** [lench4991/LenchScripterMod#3]
It would be nice to expose the inertia of single blocks and also the whole machine in the API. 
Writing control algorithms for flying machines would be so much easier.

**Comment by lench4991** [comment]
Added properties
- `InertialTensor` (Vector3)
- `InertialTensorRotation` (default as EulerAngles in degrees)
- `InertialTensorRotationQuaternion` 
- `InertialTensorRotationDeg` (EulerAngles in degrees)
- `InertialTensorRotationRad` (EulerAngles in radians)

 for each block. Hope these help.

I didn't go through with adding these properties for the whole machine, just because I'm not that familiar with physics and don't want to get it wrong, but I think you have everything you need to do that yourself (like center of mass for blocks and machine).

I'm got some other bug fixes to do. If everything works, you can expect the update shortly.

**Comment by lench4991** [comment]
https://github.com/lench4991/LenchScripterMod/releases/tag/v2.2.1
