### ISSUE TITLE
Embedding "Update()" in "Class"

### ISSUE THREAD

**Issue by HultimateH** [lench4991/LenchScripterMod#7]
Embedding "Update()" in "Class" ，like script  derives from monobehaviour in c# script

Example :
**in c# script:**
         
 public class test :  monobehaviour
{
       
&#8195;void Update() `//Update is called every frame`
       &#8195; {
&#8195;&#8195;do();
        &#8195; }          
&#8195;void do(){}

}  

**in scripter mod:**

class test:
      &#8195;def do():
            &#8195;&#8195;pass

example = test()

def Update():
&#8195;example.do()

**I hope:**
class test:
&#8195;def do():
&#8195;&#8195;pass

&#8195;def Update():`//Update is called every frame`
&#8195;&#8195;do()

example = test()

class automatically derives from MonoBehaviour,can call Update() and FixedUpdate() in class.
I think it makes the code easier to read.This is necessary in a complex script

**Comment by lench4991** [comment]
I see your point, but this doesn't really achieve anything besides complicating things.

In your example, the `Update` function is just a static member, which could be useful when loading classes from modules, but not when this script is the entrypoint. If the update functions were methods of a class, like in UnityEngine, you would need to instantiate it somewhere, which doesn't really make sense because you really only need one update entrypoint.

Perhaps some other Python tricks could help you with what you want, for example

```py
class SomeClass:
    def SomeMethod(self):
        # do something
        pass

# instantiate the class
instance = SomeClass()

# make Update point to the class method
Update = instance.SomeMethod
```
... or with a static member as in your example
```py
class SomeClass:
    def SomeMethod():
        # do something
        pass

# make Update point to the static member
Update = SomeClass.SomeMethod
```

... which doesn't really serve any purpose.
